version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HISTFILE: "/app/log/.bash_history"
    ports:
      - "3000:3000"
    tty: true
    # depends_on:
    volumes:
      - .:/app
      - rails_bundle:/app/vendor/bundle
      - node_modules:/app/node_modules

volumes:
  rails_bundle:
    driver: local
  node_modules:
    driver: local
